detectors:
  DuplicateMethodCall:
    max_calls: 3
    allow_calls:
    - 'apk.resources'
    - 'Thor::Base.shell'
    - 'CLI.command_help'
    - 'exit'
  TooManyStatements:
    exclude:
    - 'Headdesk::Checks'
    - 'Headdesk::CliCommands'
